# Post comment if there are changes in bundle size of any size
comment:
     require_bundle_changes: True
     
# Post comment if there are changes in bundle size exceeding 1Kb
comment:
     require_bundle_changes: True
     bundle_change_threshold: "1Kb"
     
# Post comment if there are changes in bundle size increases more than 1Mb
comment:
     require_bundle_changes: "bundle_increase"
     bundle_change_threshold: "1Mb"

# Post informational status (never fails) with threshold of 5%
# This is the default configuration
bundle_analysis:
	warning_threshold: "5%"
  status: "informational"
  
# Disable commit status
bundle_analysis:
  status: False
  
# Post commit status that will fail if change is larger than threshold of 10MB
bundle_analysis:
  warning_threshold: "10MB"
  status: True