changelog:
  exclude:
    labels:
      - documentation
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Security Fixes
      labels:
        - security
    - title: Other Changes
      labels:
        - '*'
