changelog:
  exclude:
    labels:
      - documentation
      - dependencies
  categories:
    - title: Added
      labels:
        - feature
    - title: Changed
      labels:
        - enhancement
    - title: Deprecated
      labels:
        - deprecated
    - title: Removed
      labels:
        - removed
        - invalid
    - title: Fixed
      labels:
        - bug
    - title: Security
      labels:
        - security
    - title: Other Changes
      labels:
        - '*'
