nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.17.0.cjs

# Do not allow installs from git repos
approvedGitRepositories: []
# Do not run post install scripts
enableScripts: false
# Require all packages to be at least 3 days old to give community time to detect
# supply chain attacks
npmMinimalAgeGate: '3d'
