version: "3.9"

services:
  inventory-management-system:
    container_name: inventory_management_system_container_frontend
    build: .
    volumes:
      - ./inventory-management-system:/inventory-management-system-run/inventory-management-system
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure
