version: '3.9'

services:
  inventory-management-system:
    container_name: inventory_management_system_container_frontend
    build: .
    volumes:
      - ./src:/inventory-management-system-run/src
      - ./public:/inventory-management-system-run/public
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure
