name: Enfore PR title convention

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-title-enforcement:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
