name: Enfore PR title convention

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr-title-enforcement:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: '^(feat|fix|docs):.*' # Regex the title should match.
          helpMessage: 'Example: feat: example of title'
